### PR TITLE
Add edit feature to image tags

### LINKED ISSUE #24: Modify Tag List
#### As a user I want to be able to edit the tag list for an image.

Acceptance criteria:
- [ ] The image whose tags are to be modified is displayed on the edit page.

### PR DESCRIPTION
**Pull request by HaominZhang**
Closes #24

### CODE REVIEW

**Comment by HaominZhang** [comment]
@rmacklin Is there any other issues I should modify me code? p.s. the review app works fine :)

**Comment by rmacklin** [comment]
@HaominZhang I left some comments directly on https://github.com/AppFolioOnboarding/Haomin_ImageUploader/commit/bd7a0efdb311bc3c7062ce100af3f9d0b47fadaa

**Comment by HaominZhang** [comment]
@rmacklin I paired with Sarah this morning and update the branch, please let me know if there is anything I should improve.

**Comment by rmacklin** [comment]
Looks good to me

**Pull request merged**
